version: '3'

dotenv:
  - .env

tasks:
  migration:
    cmds:
      - psqldef -U $DB_USER -W $DB_PASSWORD -p $DB_PORT $DB_NAME < database/sql/schema.sql
  dry-migration:
    cmds:
      - psqldef -U $DB_USER -W $DB_PASSWORD -p $DB_PORT $DB_NAME --dry-run < database/sql/schema.sql
  generate:
    cmds:
      - tables-to-go -v -t pg -h db -d $DB_NAME -u $DB_USER -p $DB_PASSWORD -pn models -port $DB_PORT -h $DB_HOST -of internal/domains/models/
      - sh ./scripts/generate_domains.sh
